[package]
name = "pozor-dom-hub"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
tokio-tungstenite = { version = "0.28", features = ["rustls-tls-webpki-roots"] }
futures-util = "0.3"
pozor-dom-shared = { path = "../pozor-dom-shared" }
